---
- name: <r_grub_t_common> template a file to /etc/default/grub
  template:
    src: grub.j2
    dest: /etc/default/grub
    owner: root
    group: root
    mode: "0644"
    #validate:
    #backup: yes
