---
- name: <r_grub_t_common> template a file to /etc/default/grub
  template:
    src: grub.j2
    dest: /etc/default/grub
    owner: root
    group: root
    mode: "0644"
    #validate:
    #backup: yes

- name: <r_grub_t_common> rebuild the grub configuration file
  command:
  #become: yes
  #become_method: su
  #become_user:
  #become_flags: "-s /bin/sh"
  args:
    cmd: grub2-mkconfig -o /etc/grub2.cfg
    #chdir:
    # A filename or (since 2.0) glob pattern.
    # If it already exists, this step *won't* be run.
    #creates:

    # A filename or (since 2.0) glob pattern.
    # If it already exists, this step *will* be run.
    #remove:
