---
- name: <r_sys_account_t_cr8_sgrps> create secondary groups
  group:
    name: "{{ v.name }}"
    gid: "{{ v.gid }}"
    state: present
  loop: "{{ sys_account_secondary_groups | dict2items }}"
  vars:
    v: "{{ item.value }}"
