---
- include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    os_distro: "{{ ansible_facts['distribution'] }}"
    os_major: "{{ ansible_facts['distribution_major_version'] }}"
    os_version: "{{ os_distro }}-{{ os_major }}"
    os_family: "{{ ansible_facts['os_family'] }}"
    params:
      files:
        - "{{ os_version }}/install.yml"
        - "{{ os_distro }}/install.yml"
        - "{{ os_family }}/install.yml"
      paths:
        - "tasks"
