---
- name: <r_nfs_server_t_setup> create export directories
  file:
    path: "{{ item.export }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
    #recurse: yes
  loop: "{{ nfs_server_shares }}"
  loop_control:
    label: "{{ item.export }}"

- name: <r_nfs_server_t_setup> template a file to /etc/exports
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: "0644"
    #backup: yes
    # The validation command to run before copying into place.
    # E.g. `validate: /usr/sbin/visudo -csf %s`
    #validate:
  notify: "({{ role_name }}) restart nfs service"
