---
- name: <r_ssh_setup_t_server_config> copy a file to /etc/ssh/sshd_config
  copy:
    # if path ends with "/", only inside contents of that
    # directory are copied to destination.
    # if it does not end with "/", the directory itself
    # with all contents is copied.
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0600"
    #backup: yes
    # The validation command to run before copying into place.
    # E.g. `validate: /usr/sbin/visudo -csf %s`
    validate: sshd -tf %s
  notify: "({{ role_name }}) restart service sshd"
