---
- name: <r_anon_ftp_t_config> template a file to /etc/vsftpd.conf
  template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd.conf
    owner: root
    group: root
    mode: "0644"
    #backup: yes
    # The validation command to run before copying into place.
    # E.g. `validate: /usr/sbin/visudo -csf %s`
    #validate:
  notify: "({{ role_name }}) restart service vsftpd"
