---
- include_vars: "{{ lookup('first_found', params) }}"
  vars:
    os_distro: "{{ ansible_facts['distribution'] }}"
    os_major: "{{ ansible_facts['distribution_major_version'] }}"
    os_version: "{{ os_distro }}-{{ os_major }}"
    os_family: "{{ ansible_facts['os_family'] }}"
    params:
      files:
        - "{{ os_version }}.yml"
        - "{{ os_distro }}.yml"
        #- "{{ os_family }}.yml"
        #- default.yml
      paths:
        - "vars"

- name: <r_pip_t_common> install pip
  yum:
    name: "{{ pip_pkg }}"
    state: present
    update_cache: yes
    disable_gpg_check: yes
    #allow_downgrade: yes
