---
- name: <r_yum_repos_t_common> remove yum repo dir and cache
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/yum.repos.d
    - "{{ '/var/cache/dnf' if os_major == '8' else '/var/cache/yum' }}"

- name: <r_yum_repos_t_common> create directory /etc/yum.repos.d
  file:
    path: /etc/yum.repos.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: <r_yum_repos_t_common> template a file to /etc/yum.repos.d/Centos-Base.repo
  template:
    src: "{{ os_version }}.repo.j2"
    dest: /etc/yum.repos.d/Centos-Base.repo
    owner: root
    group: root
    mode: "0644"
    #validate:
    #backup: yes
