---
# tasks file for users

# - import_tasks: cr8_pgrps.yml
#   tags:
#     - r_users_t_cr8_pgrps

# - import_tasks: cr8_sgrps.yml
#   tags:
#     - r_users_t_cr8_sgrps

- import_tasks: cr8_users.yml
  tags:
    - r_users_t_cr8_users
