---
- name: <r_sys_preinst_t_common> preinstall the base packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
    disable_gpg_check: yes
    #allow_downgrade: yes
  loop: "{{ preinst['cloud']['rpm_pkgs'] }}"
