---
- name: <r_vim_t_common> install vim
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
    disable_gpg_check: yes
    disable_plugin: fastestmirror
    #allow_downgrade: yes
  loop:
    - vim-enhanced
