---
- name: <r_base_kparams_t_common> template a file to /etc/sysctl.d/00-init-base.conf
  template:
    src: init_base_sysctl.sh.j2
    dest: /etc/sysctl.d/
    owner: root
    group: root
    mode: "0644"
    #backup: yes
    # The validation command to run before copying into place.
    # E.g. `validate: /usr/sbin/visudo -csf %s`
    #validate:

- name: <r_base_kparams_t_common> initialize the base sysctl config
  shell:
  #become: yes
  #become_method: su
  #become_user:
  #become_flags: "-s /bin/sh"
  args:
    cmd: /bin/bash init_bash_sysctl.sh
    chdir: /etc/sysctl.d
    # when filename already exists, this step *won't* be run.
    #creates:

    # when filename already exists, this step *will* be run.
    #remove:
