---
- name: <r_common_t_anon_config> template a file to DEST
  template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd.conf
    owner: root
    group: root
    mode: "0644"
    #backup: yes
    # The validation command to run before copying into place.
    # E.g. `validate: /usr/sbin/visudo -csf %s`
    #validate:
