---
- name: <r_anon_ftp_t_common> install the vsftpd package
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - vsftpd

- name: "<r_anon_ftp_t_common> create directory {{ anon_ftp_anon_root }}"
  file:
    path: "{{ anon_ftp_anon_root }}"
    state: directory
    owner: root
    group: ftp
    mode: "0755"
    #recurse: yes

- name: <r_anon_ftp_t_common> change the ftp user's home directory
  user:
    name: ftp
    home: "{{ anon_ftp_anon_root }}"
